### ISSUE TITLE
Potential problem with parse/error check for GetWorkitemStream

### ISSUE THREAD

**Issue by abelsquidhead** [DarqueWarrior/OKRGrader#1]
Grader.GetWorkItemStream (starting at line 169) – This method returns the request stream  based off of the request uri. In it, the last step you parse the stream looking to see if an error page exists (if “Sign In is in the text”)and if does, throw an unauthorized http request exception. 
o	What if the work item has the phrase “Sign In blah blah blah” in the description or something like that. Would it cause problems?

**Comment by DarqueWarrior** [comment]
That is a great point. If the work item has a description or title with "Sign In" in it, this could case a 401 for no reason.  I will work on a fix.

**Comment by DarqueWarrior** [comment]
Fixed in PR #2 Sorry it took so long.
